### ISSUE TITLE
Select date / time in the past

### ISSUE THREAD

**Issue by saltbieb** [itsmeichigo/DateTimePicker#51]
Hey,

how can I configure the picker so I can choose a time in the past? I've set the isTimePickerOnly value to "true" and tried to set the selected date in the future and to test it also in the past but when I want to set a time in the past it always scrolls back to the current time. Could you help me please?

Thanks in advance!

**Comment by itsmeichigo** [comment]
Hi, 

From what you just described above I can assume that you're setting your `minimumDate` as today, so you can't really select any day before current date. In order to select some time in the past, please set your `minimumDate` value to a time that is way before the time you want to select.

Cheers!
