### ISSUE TITLE
Minimum Date Selected Bug

### ISSUE THREAD

**Issue by flstrout** [itsmeichigo/DateTimePicker#62]
To recreate: Open the DateTimePicker control and select the minimum date, press the done button, re-open the control. I have been getting a crash in the show method (line: 220) of the DateTimePicker controller.
I have been getting intermittent results, sometimes it works with the minimum but will crash on the maximum. It will almost always crash on one or the other.

**Comment by itsmeichigo** [comment]
Hi, sorry for the late reply. The cause of the crash is that the selected date is earlier than the minimum date (hence the `assert`). I would suggest that you keep a fixed minimum date (other than a NSDate() for example); or if you rather update the minimum date, please make sure to set the selected date to be equal or later than the minimum date.

I'll be closing this because it's not a bug of the control.
