### ISSUE TITLE
button today not show

### ISSUE THREAD

**Issue by fukemy** [itsmeichigo/DateTimePicker#69]
can you help ? here is layout:
[Navigation]
[Customview button click]
[TableView]

Code:
```
let picker = DateTimePicker.show(selected: Date().addingTimeInterval(TimeInterval(-MININUM_MONTH_TIME_SELECT)),
                                             minimumDate: Date().addingTimeInterval(TimeInterval(-MONTH_TIME)),
                                             maximumDate:  Date())
            picker.highlightColor = UIColor(red: 255.0/255.0, green: 138.0/255.0, blue: 138.0/255.0, alpha: 1)
            picker.doneButtonTitle = "Hoàn thành"
            picker.is12HourFormat = true
            picker.todayButtonTitle = "Hôm nay"
            picker.highlightColor = UIColor(hex: "E4A21C", alpha: 1)
            picker.doneBackgroundColor = UIColor(hex: "5DB093", alpha: 1)
            picker.backgroundViewColor = UIColor(hex: "000000", alpha: 0.7)
            picker.completionHandler = { date in
                
                self.btTime.setTitle(DateFormatter.sharedDateFormatter.string(from: date), for: .normal)
                self.btTime.backgroundColor = UIColor(hex: "5DB093")
                self.btTime.titleLabel?.textColor = .white
                
                
                self.collapseViewModeButton()
            }
```

Image:
![simulator screen shot - iphone 5s - 2018-07-20 at 14 02 08](https://user-images.githubusercontent.com/8202437/42988073-826b3a6e-8c25-11e8-9c79-ee30257e89dc.png)

**Comment by itsmeichigo** [comment]
Hi, it is intentional to hide reset button when maximum date is not later than `Date()` or minimum date is not earlier than `Date()` - this is to avoid the crash when user taps on reset button (reset button always set the `selectedDate` to `Date()`.

As I see in your code your maximum date is `Date()` - then when user taps on reset button the date will be `Date()`, at that time there's a high chance that the selected date is later than maximum date, which is not the wanted behavior for the picker and will crash the app.

**Comment by fukemy** [comment]
Hi, now I know your intentional.

My project is about review the passed time, so the maximum data always < Date.now. Can you provide some suggest? 

 Best regards.

**Comment by itsmeichigo** [comment]
May I ask what do you expect the reset button to do? Since it should not set selected date to `Date()`. A quick solution would be that you fork my lib and customize the reset button to do what you want. I can add a block property for custom reset button behavior but I'm not sure many people need that.

**Comment by fukemy** [comment]
thanks you, i will fork your lib and modify code.

**Comment by itsmeichigo** [comment]
I’ll close this issue since it’s not really an issue from my lib.
