### ISSUE TITLE
unable to set maximum Time upto a particular day?

### ISSUE THREAD

**Issue by SuganyaEkambaram** [itsmeichigo/DateTimePicker#75]
tried with date components

**Comment by itsmeichigo** [comment]
@SuganyaEkambaram  Please use the following template to specify the issue you're encountering so I can have a better understanding of it:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Library and Device details (please complete the following information):**
 - Library version: [e.g. 2.1.0]
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]

**Additional context**
Add any other context about the problem here.
